---

version: 2

formats: all

build:
  os: "ubuntu-22.04"
  tools:
    # NOTE: `docs/conf.py` uses `importlib.metadata`, which needs Python 3.8+.
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
  install:
  # - requirements: .docs-requirements.txt
  # - method: pip
  #   path: pip >= 19.0.3
  - method: pip
    path: .
    extra_requirements:
    - docs

...
